apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: fraud-detection
  namespace: default
spec:
  name: fraud-detection
  annotations:
    project_name: fraud_detection_service
    deployment_version: v1
  predictors:
    - name: xgb
      replicas: 1
      traffic: 100
      componentSpecs:
        - spec:
            containers:
              - image: fraud-classifier:xgb
                imagePullPolicy: IfNotPresent
                name: xgb
                env:
                  - name: VERSION
                    value: "XGBoost"
            terminationGracePeriodSeconds: 1
      graph:
        children: []
        endpoint:
          type: REST
        name: xgb
        type: MODEL